ShoppingSolution/Portal/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using Common;
using DAL;
using Microsoft.AspNet.Identity;
using Model;
using Portal.Infrastructure;

namespace Portal.Controllers
{
    //[Authorize]
    public class CustomerController : Controller
    {
        //
        // GET: /Customer/
        public ActionResult Products()
        {
            var products = new ProductBLL().GetAllProducts() ?? new List<Product>();
            return View(products);
        }

        public JsonResult AddToCart(string pId)
        {
            if (string.IsNullOrWhiteSpace(pId))
            {
                return MvcHelper.CreateJsonError(Constants.InvalidInputData);
            }
            new CustomerBLL().AddProductToCustomerCart(pId, User.Identity.GetUserId(), 1);
            return MvcHelper.CreateJsonSuccessResult();
        }

        [HttpGet]
        public ActionResult GetMyCart(string pId)
        {
            if (string.IsNullOrWhiteSpace(pId))
            {
                return MvcHelper.CreateJsonError(Constants.InvalidInputData);
            }
            var myCart = new CustomerBLL().GetCustomerShoppingCart(User.Identity.GetUserId(), ShoppingCartStatus.ACTIVE);
            return View(myCart);
        }                   
    }
}

ShoppingSolution/Portal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ShoppingSolution/Portal/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using BLL;
using Common;
using Portal.Infrastructure;
using Portal.Models;
using Model;

namespace Portal.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/
        public ActionResult Products()
        {
            var products = new ProductBLL().GetAllProducts() ?? new List<Product>();
            return View(products);
        }

        //
        // GET: /Product/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductCreateVM model)
        {
            try
            {
                if (ModelState.IsValid == false)
                {
                    return View(model);
                }
                new ProductBLL().AddProduct(Mapper.ToProduct(model));
                return RedirectToAction("Products");
            }
            catch
            {
                return View();
            }
        }   

        //
        // GET: /Product/Delete/5
        public JsonResult Delete(string pId)
        {
            if (string.IsNullOrWhiteSpace(pId))
            {
                return MvcHelper.CreateJsonError(Constants.InvalidInputData);                
            }
            new ProductBLL().RemoveProduct(pId);
            return MvcHelper.CreateJsonSuccessResult();
        }

    }
}

ShoppingSolution/Portal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ShoppingSolution/Portal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ShoppingSolution/Portal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Shopping cart</h1>
    <p class="lead">Online shopping using asp.net MVC razor views, JS, MSSQL, EF 6.0 technologies.</p>    
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Manage Products</h2>
      
        <p>@Html.ActionLink("Manage Products", "Products", "Product", null, new { @class = "btn btn-default" })</p>        
    </div>
    <div class="col-md-4">
        <h2>Customer</h2>
        <p>@Html.ActionLink("Customer view", "Products", "Customer", null, new {@class="btn btn-default"})</p>
    </div>   
</div>